ARG BASE_TAG="develop"
FROM kasmweb/core-ubuntu-bionic:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

RUN echo '--ipv4' > /root/.curlrc
RUN echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4
RUN apt update && apt install -y apt-transport-https ca-certificates sudo
COPY ./src/sources.list /etc/apt/sources.list

RUN useradd kasm_user && echo "kasm_user:password" | chpasswd && echo "kasm_user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/kasm_user

# Add Kasm Branding
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN cp /usr/share/extra/icons/icon_kasm.png /usr/share/extra/icons/icon_default.png
RUN sed -i 's/ubuntu-mono-dark/elementary-xfce/g' $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

# Install Utilities
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/

# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

# Install Custom Certificate Authority
# COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
# RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/


COPY ./src/ubuntu/install/remmina $INST_SCRIPTS/remmina/
RUN bash $INST_SCRIPTS/remmina/install_remmina.sh  && rm -rf $INST_SCRIPTS/remmina/

COPY ./src/ubuntu/install/remmina/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

RUN mkdir $HOME/.config/remmina/
COPY ./src/ubuntu/install/remmina/remmina.pref $HOME/.config/remmina/remmina.pref
RUN chown -R 1000:1000 $HOME/.config/remmina/

ENV XMODIFIERS="@im=ibus"
ENV QT_IM_MODULE="ibus"
ENV GTK_IM_MODULE="ibus"

RUN mkdir -p /tmp/tools/
COPY ./src/custom/ttf-wps-fonts /tmp/tools/ttf-wps-fonts
RUN ls /tmp/tools && bash /tmp/tools/ttf-wps-fonts/install.sh && rm -rf /tmp/tools

# RUN apt update && apt install -y sudo libxkbcommon-x11-0 libxcb-xinerama0 libxslt-dev ibus ibus-sunpinyin ttf-mscorefonts-installer fonts-wqy-zenhei ibus-gtk ibus-gtk3

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER kasm_user
